version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: foodmania_user
      POSTGRES_PASSWORD: foodmania_password
      POSTGRES_DB: foodmania
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foodmania_user -d foodmania"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://foodmania_user:foodmania_password@db:5432/foodmania?schema=public
      - JWT_SECRET=your_jwt_secret_here
      - STRIPE_SECRET_KEY=your_stripe_secret_key_here
      - STRIPE_WEBHOOK_SECRET=your_webhook_secret_here
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./foodmania_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_STRIPE_PUBLISHABLE_KEY=your_stripe_publishable_key_here
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
