services:
  - type: web
    name: foodmania-backend
    runtime: node
    buildCommand: cd backend && npm run render-build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: foodmania-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://foodmania.onrender.com
    plan: free

  - type: web
    name: foodmania-frontend
    runtime: node
    buildCommand: cd foodmania_frontend && npm install && npm run build
    envVars:
      - key: VITE_API_URL
        value: https://foodmania-backend.onrender.com
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
    plan: free

databases:
  - name: foodmania-db
    databaseName: foodmania
    user: foodmania_user
    plan: free
